project:
  type: book
  output-dir: ../docs

book:
  title: "P02：金融数据获取、管理与初步分析"
  author: "李贤记"
  date: "2026-04-08"
  chapters:
    - index.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd

format:
  html:
    theme: cosmo
    lang: zh
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
