project:
  type: book
  output-dir: docs

book:
  title: "P02 Financial Data Analysis"
  author: "Li Xianji"
  chapters:
    - index.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd

format:
  html:
    theme: cosmo
